### ISSUE TITLE
Broken with DMS 2.1.1

### ISSUE THREAD

**Issue by ViceIce** [manuelm/pvr.dvbviewer#28] opened 2018-05-18 14:57 UTC
Hi,

The add-on does not show anything since I upgraded the DMS from 2.0.4 to 2.1.1.

If required, I can send some logs the next days.

My environment is Kodi 17.6 on Amazon FireTv.

**Comment by manuelm** [comment] 2018-05-18 18:59
Afaik there was no imcompatible change in DMS 2.1. So the PVR should be running fine.

However there won't be any more Krypton minor releases. So all you can do is upgrade to Kodi Leia (Nightly) anyway. I'm running Kodi Leia (Nightly) + DMS 2.1 myself for quit some time.

**Comment by manuelm** [comment] 2018-05-18 19:09
However feel free to create and send a full debug log. But I do think that the issue is not PVR related and an upgrade/Nightly wont help.

Is playback from the DMS webinterface working?

**Comment by ViceIce** [comment] 2018-05-25 04:26
Ok, found some errors in the log:

```
06:24:04.826 T:56868   ERROR: CDatabase::CommitInsertQueries - failed to execute queries
06:24:04.841 T:56868   ERROR: SQL: [TV29.db] Abort due to constraint violation
                                            Query: INSERT INTO channels (iUniqueId, bIsRadio, bIsHidden, bIsUserSetIcon, bIsUserSetName, bIsLocked, sIconPath, sChannelName, bIsVirtual, bEPGEnabled, sEPGScraper, iLastWatched, iClientId, idEpg) VALUES (18, 0, 0, 0, 0, 0, 'http://192.168.158.3:8089/logos/deluxemusic.png', 'DELUXE MUSIC', 0, 1, 'client', 0, 27186753, -1)
```

Looks like i have to recreate the `tv29.db`.

**Comment by manuelm** [comment] 2018-06-08 21:45
I'm closing this for now. Feel free to reopen if you have more input.

**Closed** 2018-06-08 21:46 UTC
